{
 "title": "CCF Home Page",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Response Time (s)",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "avg by (action) (avg_over_time({suite=\"CCF HomePage\", type=\"testcase\"} | unwrap duration [30s])/1000)"
    }
   ]
  },
  {
   "title": "Response Time All (ms)",
   "type": "timeseries",
   "gridPos": { "h": 16, "w": 11, "x": 12, "y": 0 },
   "targets": [
    {
     "expr": "avg by (action) (avg_over_time({suite=\"CCF HomePage\", action!=\"\\\"${url}\\\" != \\\"https://mabanque.ccf.fr/public/attente\\\"\", action!=\"\\\"${url}\\\" == \\\"https://mabanque.ccf.fr/public/attente\\\"\", action!=\"BuiltIn.Sleep|3 s\"} | unwrap duration [30s]))"
    }
   ]
  },
  {
   "title": "Transactions Status Count",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "count by (status) (count_over_time({suite=\"CCF HomePage\", action=\"CCF Home Page\"}  | json[15m]))",
     "legendFormat": "CCF Home Page {{status}}"
    },
    {
     "expr": "count by (status) (count_over_time({suite=\"CCF HomePage\", action=\"CCF Check FAQ\"}  | json[15m]))",
     "legendFormat": "CCF Check FAQ  {{status}}"
    }
   ]
  }
 ]
}